version: '3'

services:
    pandoc:
        image: jagregory/pandoc
        volumes:
          - ./:/source
        command: -s --toc manual/MANUAL.md -o docs/index.html

    deb:
        build: ./src/packaging/deb
        volumes:
          - ./:/data
