# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
              sudo apt-get update -qq
              sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
              sudo pip install pyYaml ccm


      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Download ccm
          command: |
            ccm create test_2_2 --no-switch -v 2.2.13
            ccm create test_3_0 --no-switch -v 3.0.17
            ccm create test_3_11 --no-switch -v 3.11.3

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.ccm/repository

          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: gradle test

      - run:
          name: Start CCM and run tests
          command: |
            mkdir -p /home/circleci/.local
            ccm create test -v 3.11.3 -n 3

            echo "-Xmx500m" >> /home/circleci/.ccm/test/node1/conf/jvm.options
            echo "-Xmx500m" >> /home/circleci/.ccm/test/node2/conf/jvm.options
            echo "-Xmx500m" >> /home/circleci/.ccm/test/node3/conf/jvm.options

            echo "-Xms500m" >> /home/circleci/.ccm/test/node1/conf/jvm.options
            echo "-Xms500m" >> /home/circleci/.ccm/test/node2/conf/jvm.options
            echo "-Xms500m" >> /home/circleci/.ccm/test/node3/conf/jvm.options

            echo "-Xmn200m" >> /home/circleci/.ccm/test/node1/conf/jvm.options
            echo "-Xmn200m" >> /home/circleci/.ccm/test/node2/conf/jvm.options
            echo "-Xmn200m" >> /home/circleci/.ccm/test/node3/conf/jvm.options

            ccm start --verbose

            ./gradlew assemble

            ls build/libs

            bin/tlp-stress run KeyValue





