# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

aliases:
  base_job: &base_job
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

commands:
  install_ccm:
    description: "Installs and starts CCM"
    parameters:
      version:
        type: string
        default: "2.2.14"
      cluster_name:
        type: string
        default: "test"

    steps:
      - restore_cache:
        - keys:
          - ccm

      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
      - run: sudo pip install pyYaml ccm
      - run: ccm create << parameters.cluster_name >> -n 1 -v << parameters.version >>
      - run:
          name: "Adjust cluster parameters"
          command: |
            for i in `seq 1 3` ; do
              sed -i 's/#MAX_HEAP_SIZE="4G"/MAX_HEAP_SIZE="136m"/' ~/.ccm/test/node$i/conf/cassandra-env.sh
              sed -i 's/#HEAP_NEWSIZE="800M"/HEAP_NEWSIZE="112M"/' ~/.ccm/test/node$i/conf/cassandra-env.sh
            done

      - run: ccm start
      - run: ccm status
      - run: ccm checklogerror
      - run: ccm node1 nodetool status

  gradle_test:
    description: "Run gradle test and deal with caches"
    steps:
      - restore_cache:
          keys:
            - deps-{{ checksum "build.gradle" }}
      - run: ./gradlew test -i
      - save_cache:
          key: deps-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches


jobs:

  build:
    <<: *base_job

    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
      - run: sudo pip install pyYaml ccm

      - run:
          name: Download CCM for Cache
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y libjna-java python-dev python-pip libyaml-dev nodejs
            sudo pip install pyYaml ccm
            ccm create cassanda_21 --no-switch -v 2.1.20
            ccm create cassandra_22 --no-switch -v 2.2.13
            ccm create cassandra_30 --no-switch -v 3.0.17
            ccm create cassandra_311 --no-switch -v 3.11.4

      - save_cache:
          key: ccm
          paths:
            - ~/.ccm/repository

      - run: ./gradle testClasses

  cassandra_21:
    <<: *base_job

    steps:
      - checkout
      - install_ccm:
          version: 2.1.20
          cluster_name: cassandra_21

      - run: ./gradlew test

  cassandra_3:
    <<: *base_job

    steps:
      - checkout
      - install_ccm:
          version: 3.0.17
          cluster_name: cassandra_3

      - run: ./gradlew test


